import React, { ReactNode } from 'react';
import Head from 'next/head';
import Header from './Header';

interface Props {
  children: ReactNode
}
const Layout:React.FC<Props> = ({children}) => {
  return (
    <div>
    <Head>
    <title>Coinfunr.</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
    <Header/>
   {children}
  </main>
</div>
  )
}

export default Layout;