
export const data = [
    {
        id: 0,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: 'Help Dustin the Cat',
        organiser: 'Femi Abubakar',
        goal: 5000,
        currentRaised: 1537,
        donations: 230,
        tag: 'Animals',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: true,

    },
    {
        id: 1,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: `Help pay for Bola's School Fees`,
        organiser: 'Olawale Buhari',
        goal: 43000,
        currentRaised: 34590,
        donations: 1535,
        tag: 'Family',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small'
    },
    {
        id: 2,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: 'Help the Nothern Almajiris',
        organiser: 'Uche Adegoke',
        goal: 120000,
        currentRaised: 34450,
        donations: 4300,
        tag: 'Community',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: true,


    },
    {
        id: 3,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: 'Help Dustin the Cat',
        organiser: 'Femi Abubakar',
        goal: 5000,
        currentRaised: 1537,
        donations: 230,
        tag: 'Animals',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: true,

    },
    {
        id: 4,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: `Help pay for Bola's School Fees`,
        organiser: 'Olawale Buhari',
        goal: 43000,
        currentRaised: 34590,
        donations: 1535,
        tag: 'Family',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: true,


    },
    {
        id: 5,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: 'Help the Nothern Almajiris',
        organiser: 'Uche Adegoke',
        goal: 120000,
        currentRaised: 34450,
        donations: 4300,
        tag: 'Community',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: false,


    },
    {
        id: 6,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: 'Help Dustin the Cat',
        organiser: 'Femi Abubakar',
        goal: 5000,
        currentRaised: 1537,
        donations: 230,
        tag: 'Animals',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: false,

    },
    {
        id: 7,
        img: '/dustin_the_cat.png',
        imgTwo: '/human-right.png',
        nft: '/nft.png',
        name: `Help pay for Bola's School Fees`,
        organiser: 'Olawale Buhari',
        goal: 43000,
        currentRaised: 34590,
        donations: 1535,
        tag: 'Family',
        description: 'Hi, my name is Femi and I am fundraising for Dustin’s surgery. Dustin is a stray who I found hurt really badly on the streets. I managed to catch him and take him to the vet and it seems like the poor thing has been hurt for at least a couple of months. The costs were extremely high but my heart wouldn’t let me allow tiger to die just for financial reasons when he had full chance of recovery and living a painless , happy life. Anything helps , no matter how small',
        isOpen: true,


    }
]