import Head from 'next/head';
import Image from 'next/image';
import Rating from '@mui/material/Rating';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-red-500'>
          Happy coding
        </h1>
        {/* <Rating
        name="simple-controlled"
      /> */}
      </main>
    </div>
  )
}
